# the compiler: gcc for C program, g++ for C++
CC = gcc

# compiler flags
# -g adds debugging information to the executable file
# -Wall turns on most but not all compiler warnings
CFLAGS = -Wall -g

TARGET = ex9 ex9b ex9e ex9e2 ex9e3

all: $(TARGET)

clean:
	rm -f $(TARGET)

