# the compiler: gcc for C program, g++ for C++
CC = gcc

# compiler flags
# -g adds debugging information to the executable file
# -Wall turns on most but not all compiler warnings
CFLAGS = -Wall -g

TARGET = ex17pre ex17 ex17e ex17e1 ex17e2 ex17e3 ex17e4 ex17b

all: $(TARGET)

clean:
	rm -f $(TARGET) *.db

