# the compiler: gcc for C program, g++ for C++
CC = gcc

# compiler flags
# -g    adds debugging information to the executable file
# -Wall turns on most but not all compiler warnings
CFLAGS = -Wall -g

TARGET = ex1 ex3 ex11 ex12 ex13 ex14

all: $(TARGET)

clean:
	rm -f $(TARGET)

