# the compiler: gcc for C program, g++ for C++
CC = gcc

# compiler flags
# -g adds debugging information to the executable file
# -Wall turns on most but not all compiler warnings
CFLAGS = -Wall -g

TARGET = ex10 ex10b ex10e ex10e1

all: $(TARGET)

clean:
	rm -f $(TARGET)

