# the compiler: gcc for C program, g++ for C++
CC = gcc

# compiler flags
# -g adds debugging information to the executable file
# -Wall turns on most but not all compiler warnings
CFLAGS = -Wall -g

TARGET = ex12 ex12b ex12e

all: $(TARGET)

clean:
	rm -f $(TARGET)

