# the compiler: gcc for C program, g++ for C++
CC = gcc

# compiler flags
# -g adds debugging information to the executable file
# -Wall turns on most but not all compiler warnings
CFLAGS = -Wall -g

TARGET = ex11 ex11e ex11b 

all: $(TARGET)

clean:
	rm -f $(TARGET)

